export const S = {
    app: { fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif", background: "#f1f5f9", minHeight: "100vh", color: "#0f172a" },
    loading: { minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", color: "#64748b" },
    onboardBg: { minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "linear-gradient(160deg,#0f172a,#1e293b,#0f172a)", padding: 18, width: "100%", boxSizing: "border-box" },
    onboardCard: { background: "rgba(30,41,59,0.9)", backdropFilter: "blur(20px)", borderRadius: 22, padding: "32px 24px", width: "100%", maxWidth: 380, textAlign: "center", border: "1px solid rgba(255,255,255,0.08)", display: "flex", flexDirection: "column", alignItems: "center", margin: "0 auto" },
    onboardIcon: { width: 52, height: 52, borderRadius: 14, background: "linear-gradient(135deg,#3b82f6,#8b5cf6)", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", fontWeight: 900, fontSize: 24, marginBottom: 12, boxShadow: "0 6px 20px rgba(99,102,241,0.3)" },
    onboardTitle: { color: "#fff", fontSize: 20, fontWeight: 900, margin: "0 0 4px" },
    onboardSub: { color: "#94a3b8", fontSize: 13, marginBottom: 18 },
    storeBtn: { padding: "16px 14px", borderRadius: 14, border: "none", background: "rgba(255,255,255,0.06)", color: "#f8fafc", cursor: "pointer", display: "flex", flexDirection: "column", alignItems: "center", gap: 6, transition: "all 0.15s", width: "100%" },
    adminLink: { marginTop: 16, padding: "8px 16px", borderRadius: 8, border: "1px solid rgba(255,255,255,0.1)", background: "none", color: "#94a3b8", fontSize: 12, cursor: "pointer" },
    backBtn: { alignSelf: "flex-start", background: "none", border: "none", color: "#94a3b8", fontSize: 12, cursor: "pointer", marginBottom: 8, padding: 0 },
    header: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 18px", background: "#0f172a", color: "#f8fafc", position: "sticky", top: 0, zIndex: 50, boxShadow: "0 4px 12px rgba(0,0,0,0.2)" },
    hLeft: { display: "flex", alignItems: "center", gap: 9 },
    logo: { width: 34, height: 34, borderRadius: 8, background: "linear-gradient(135deg,#3b82f6,#8b5cf6)", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 900, fontSize: 17, color: "#fff" },
    hTitle: { fontWeight: 800, fontSize: 15 },
    hSub: { fontSize: 11, color: "#cbd5e1" },
    hRight: { display: "flex", alignItems: "center", gap: 8 },
    dateBadge: { padding: "4px 9px", borderRadius: 6, background: "rgba(255,255,255,0.1)", fontSize: 11, fontWeight: 600 },
    logoutBtn: {
        padding: "7px 14px",
        borderRadius: 8,
        background: "linear-gradient(135deg, #dc2626, #991b1b)",
        color: "#fff",
        border: "none",
        fontSize: 12,
        fontWeight: 700,
        cursor: "pointer",
        boxShadow: "0 2px 8px rgba(220, 38, 38, 0.3)",
        transition: "all 0.2s",
        display: "flex",
        alignItems: "center",
        gap: 6
    },
    toast: { position: "fixed", top: 60, left: "50%", transform: "translateX(-50%)", padding: "9px 20px", borderRadius: 10, background: "#16a34a", color: "#fff", fontWeight: 700, fontSize: 13, zIndex: 200, boxShadow: "0 6px 20px rgba(0,0,0,0.2)" },
    toastErr: { background: "#dc2626" },
    tabBar: { display: "flex", background: "#fff", borderBottom: "1px solid #e2e8f0", overflowX: "auto", padding: "0 10px" },
    tab: { padding: "11px 14px", border: "none", background: "none", fontSize: 12, fontWeight: 600, color: "#64748b", cursor: "pointer", borderBottom: "2px solid transparent", whiteSpace: "nowrap", display: "flex", alignItems: "center", gap: 4 },
    tabActive: { color: "#0f172a", borderBottomColor: "#3b82f6", fontWeight: 700 },
    adminContent: { padding: "18px 20px 100px", maxWidth: 900, margin: "0 auto" },
    dateFilter: { display: "flex", alignItems: "center", gap: 8, marginBottom: 14, flexWrap: "wrap" },
    dateBtn: { width: 34, height: 34, borderRadius: 7, border: "1px solid #e2e8f0", background: "#fff", cursor: "pointer", fontSize: 14, fontWeight: 700 },
    segBtn: { padding: "6px 10px", minWidth: 56, height: 32, borderRadius: 7, border: "1px solid #e2e8f0", background: "#fff", cursor: "pointer", fontSize: 12, fontWeight: 700 },
    segBtnActive: { background: "#0f172a", color: "#fff", borderColor: "#0f172a" },
    dateInput: { padding: "6px 10px", borderRadius: 7, border: "1px solid #e2e8f0", fontSize: 12, fontFamily: "'JetBrains Mono', monospace" },
    todayBtn: { padding: "7px 12px", borderRadius: 7, background: "#0f172a", color: "#fff", border: "none", fontSize: 11, fontWeight: 700, cursor: "pointer" },
    statCards: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(145px, 1fr))", gap: 8, marginBottom: 18 },
    statCard: { padding: 14, borderRadius: 11, background: "#fff", border: "1px solid #e2e8f0" },
    sectionTitle: { fontSize: 14, fontWeight: 800, margin: "18px 0 8px" },
    card: { padding: 14, borderRadius: 11, background: "#fff", border: "1px solid #e2e8f0", marginBottom: 8 },
    empty: { padding: 30, textAlign: "center", color: "#94a3b8", fontSize: 13, background: "#fff", borderRadius: 11, border: "1px dashed #e2e8f0" },
    btnSmG: { padding: "6px 12px", borderRadius: 7, background: "#16a34a", color: "#fff", border: "none", fontSize: 11, fontWeight: 700, cursor: "pointer" },
    btnSmR: { padding: "6px 12px", borderRadius: 7, background: "#dc2626", color: "#fff", border: "none", fontSize: 11, fontWeight: 700, cursor: "pointer" },
    btnSubmit: { width: "100%", padding: 13, borderRadius: 11, background: "#0f172a", color: "#fff", border: "none", fontWeight: 800, fontSize: 14, cursor: "pointer", marginTop: 12 },
    tTag: { display: "inline-block", padding: "1px 4px", borderRadius: 3, background: "#ede9fe", color: "#7c3aed", fontSize: 9, fontWeight: 700, marginRight: 3 },
    overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.55)", display: "flex", alignItems: "flex-end", justifyContent: "center", zIndex: 100, backdropFilter: "blur(4px)" },
    modal: { background: "#fff", borderRadius: "18px 18px 0 0", width: "100%", maxWidth: 520, maxHeight: "90vh", overflow: "auto" },
    modalHint: { fontSize: 12, color: "#64748b", margin: "0 0 8px" },
    formLabel: { display: "block", fontSize: 11, fontWeight: 700, color: "#475569", marginBottom: 3, marginTop: 10 },
    formInput: { width: "100%", padding: "9px 11px", borderRadius: 8, border: "1px solid #e2e8f0", fontSize: 14, boxSizing: "border-box", background: "#f8fafc" },
    errorMsg: { padding: "6px 10px", borderRadius: 6, background: "#fee2e2", color: "#dc2626", fontSize: 12, fontWeight: 600, marginTop: 6 },
    fundMaxBtn: { padding: "3px 8px", borderRadius: 5, background: "#ede9fe", color: "#7c3aed", border: "none", fontSize: 10, fontWeight: 700, cursor: "pointer" },
    countHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
    countLabel: { fontWeight: 700, fontSize: 12, color: "#475569" },
    countTotal: { fontWeight: 800, fontSize: 15, fontFamily: "'JetBrains Mono', monospace" },
    denomGrid: { display: "flex", flexDirection: "column", gap: 2 },
    denomRow: { display: "flex", alignItems: "center", gap: 5, padding: "2px 0" },
    denomValue: { width: 70, fontSize: 12, fontWeight: 600, fontFamily: "'JetBrains Mono', monospace", color: "#475569" },
    denomInputWrap: { display: "flex", alignItems: "center", flex: 1 },
    denomBtn: { width: 28, height: 28, borderRadius: 5, border: "1px solid #e2e8f0", background: "#f8fafc", cursor: "pointer", fontSize: 14, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center" },
    denomInput: { width: 44, textAlign: "center", padding: "4px", border: "1px solid #e2e8f0", borderRadius: 5, fontSize: 13, fontFamily: "'JetBrains Mono', monospace", margin: "0 1px" },
    denomSubtotal: { width: 80, textAlign: "right", fontSize: 12, fontWeight: 600, fontFamily: "'JetBrains Mono', monospace" },
    toggleCoins: { width: "100%", padding: "5px", border: "none", background: "none", color: "#64748b", fontSize: 11, fontWeight: 600, cursor: "pointer", marginTop: 3, textAlign: "left" },
    grandTotal: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "11px 13px", borderRadius: 9, background: "#0f172a", color: "#fff", marginTop: 8, fontSize: 12, fontWeight: 700 },
    grandTotalVal: { fontSize: 19, fontWeight: 900, fontFamily: "'JetBrains Mono', monospace" },
    cajWrap: { padding: "12px 16px 100px", maxWidth: 520, margin: "0 auto" },
    cajStat: { padding: 11, borderRadius: 9, background: "#fff", border: "1px solid #e2e8f0" },
    cajStatL: { fontSize: 10, color: "#64748b", marginBottom: 1 },
    cajStatV: { fontSize: 17, fontWeight: 800, fontFamily: "'JetBrains Mono', monospace" },
};
